targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - document_ignores
            - unnecessary_cast
            - require_trailing_commas
            - rexios_lints/not_null_assertion
